name: Deploy to STRATO

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code holen
        uses: actions/checkout@v4

      - name: Node installieren
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Pakete installieren
        run: npm install

      - name: Webseite bauen
        run: npm run build

      - name: Zu STRATO hochladen
        uses: milanmk/actions-file-deployer@1.18
        with:
          remote-protocol: sftp
          remote-host: ${{ secrets.STRATO_HOST }}
          remote-port: ${{ secrets.STRATO_PORT }}
          remote-user: ${{ secrets.STRATO_USER }}
          remote-password: ${{ secrets.STRATO_PASSWORD }}
          local-path: dist
          remote-path: ${{ secrets.STRATO_PATH }}
          sync: delta
