name: Deploy to STRATO

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code holen
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Zu STRATO hochladen
        uses: milanmk/actions-file-deployer@1.18
        with:
          remote-protocol: sftp
          remote-host: ${{ secrets.STRATO_HOST }}
          remote-port: ${{ secrets.STRATO_PORT }}
          remote-user: ${{ secrets.STRATO_USER }}
          remote-password: ${{ secrets.STRATO_PASSWORD }}
          local-path: .
          remote-path: ${{ secrets.STRATO_PATH }}
          sync: full
          remote-path: ${{ secrets.STRATO_PATH }}
          sync: delta
